### ISSUE TITLE
"Class extends value undefined is not a constructor or null"

### ISSUE THREAD

**Issue by kibertoad** [mattiasrunge/sftp-fs#1]
I get this error when I try to extend from FileSystem:

```
C:\sources2\lms-api\api\node_modules\sftp-fs\impl\FileSystem.js:74
class FileSystem extends FileSystemInterface {
                         ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:\sources2\lms-api\api\node_modules\sftp-fs\impl\FileSystem.js:74:26)
```

**Comment by kibertoad** [comment]
Actually, just including require('sftp-fs'); in the code causes this error.
Only if
`    ImplFileSystem: require("./impl/FileSystem"),`
is removed from index.js, it stops crashing.

**Comment by kibertoad** [comment]
On a second look, this is the result of circular dependency - FileSystem includes require("../index");
while index includes FileSystem

**Comment by mattiasrunge** [comment]
Integrated your solution for this, thanks!
