### ISSUE TITLE
Multiple authentication methods are handled wrong

### ISSUE THREAD

**Issue by kibertoad** [mattiasrunge/sftp-fs#2]
Typically clients (e. g. Filezilla) list multiple authentication methods (e. g. ['none', 'password']). However, sftp-fs seems to process only the first one and fail if it is not accepted. Authentication action should be retried with all the authentication methods.

**Comment by kibertoad** [comment]
Clarification - what is actually happening is that expected flow for unsupported authentication methods is that ss2 rejects with an array of supported auth methods and client sends follow-up request with correct authentication method. This is currently is not possible in sftp-fs as reject happens without any parameters. I have fixed this in my fork if you would like an example.

**Comment by kibertoad** [comment]
Clarification - what is actually happening is that expected flow for unsupported authentication methods is that ss2 rejects with an array of supported auth methods and client sends follow-up request with correct authentication method. This is currently is not possible in sftp-fs as reject happens without any parameters. I have fixed this in my fork if you would like an example.

**Comment by mattiasrunge** [comment]
Looked at your fork and integrated your solution, thank you! Added the contributor section as well, I hope that was okey.
